const ERROR = 'error';
const WARN = 'warn';
const DISABLE = 'off';

module.exports = {
    env: {
        'browser': true,
        'commonjs': true,
        'es6': true
    },

    globals: {
        '$': true,
        'jQuery': true
    },

    rules: {

        // Possible errors / http://eslint.org/docs/rules/#possible-errors
        'for-direction': ERROR,
        'no-await-in-loop': ERROR,
        'no-compare-neg-zero': ERROR,
        'no-cond-assign': ERROR,
        'no-console': WARN,
        'no-constant-condition': ERROR,
        'no-debugger': ERROR,
        'no-dupe-args': ERROR,
        'no-dupe-keys': ERROR,
        'no-duplicate-case': ERROR,
        'no-empty': ERROR,
        'no-empty-character-class': ERROR,
        'no-ex-assign': ERROR,
        'no-extra-boolean-cast': ERROR,
        'no-extra-parens': DISABLE,
        'no-extra-semi': ERROR,
        'no-func-assign': ERROR,
        'no-inner-declarations': ERROR,
        'no-invalid-regexp': ERROR,
        'no-irregular-whitespace': ERROR,
        'no-obj-calls': ERROR,
        'no-prototype-builtins': DISABLE,
        'no-regex-spaces': ERROR,
        'no-sparse-arrays': ERROR,
        'no-template-curly-in-string': ERROR,
        'no-unexpected-multiline': ERROR,
        'no-unreachable': ERROR,
        'no-unsafe-finally': ERROR,
        'no-unsafe-negation': ERROR,
        'use-isnan': ERROR,
        'valid-jsdoc': [ERROR, {'requireReturn': false}],
        'valid-typeof': ERROR,

        // Best practices / http://eslint.org/docs/rules/#best-practices
        'accessor-pairs': [ERROR, {'getWithoutSet': false, 'setWithoutGet': true}],
        'array-callback-return': DISABLE,
        'block-scoped-var': ERROR,
        'class-methods-use-this': DISABLE,
        'complexity': ERROR,
        'consistent-return': ERROR,
        'curly': ERROR,
        'default-case': ERROR,
        'dot-location': [ERROR, 'property'],
        'dot-notation': ERROR,
        'eqeqeq': [ERROR, 'smart'],
        'guard-for-in': DISABLE,
        'no-alert': DISABLE,
        'no-caller': ERROR,
        'no-div-regex': ERROR,
        'no-else-return': ERROR,
        'no-empty-function': ERROR,
        'no-empty-pattern': ERROR,
        'no-eq-null': ERROR,
        'no-eval': ERROR,
        'no-extend-native': ERROR,
        'no-extra-bind': ERROR,
        'no-extra-label': ERROR,
        'no-fallthrough': ERROR,
        'no-floating-decimal': ERROR,
        'no-implicit-coercion': [ERROR, {'boolean': false, 'number': true, 'string': true}],
        'no-implicit-globals': DISABLE,
        'no-implied-eval': ERROR,
        'no-invalid-this': DISABLE,
        'no-iterator': ERROR,
        'no-labels': ERROR,
        'no-lone-blocks': ERROR,
        'no-loop-func': ERROR,
        'no-magic-numbers': DISABLE,
        'no-multi-spaces': DISABLE,
        'no-multi-str': ERROR,
        'no-new': ERROR,
        'no-new-func': ERROR,
        'no-new-wrappers': ERROR,
        'no-octal': ERROR,
        'no-octal-escape': ERROR,
        'no-param-reassign': DISABLE,
        'no-proto': ERROR,
        'no-redeclare': ERROR,
        'no-restricted-properties': DISABLE,
        'no-return-assign': ERROR,
        'no-return-await': ERROR,
        'no-script-url': ERROR,
        'no-self-assign': [ERROR, {props: true}],
        'no-self-compare': ERROR,
        'no-sequences': ERROR,
        'no-throw-literal': ERROR,
        'no-unmodified-loop-condition': ERROR,
        'no-unused-expressions': ERROR,
        'no-unused-labels': ERROR,
        'no-useless-call': ERROR,
        'no-useless-concat': ERROR,
        'no-useless-escape': ERROR,
        'no-useless-return': ERROR,
        'no-void': ERROR,
        'no-warning-comments': [ERROR, {'terms': ['fixme', 'xxx'], 'location': 'start'}],
        'no-with': ERROR,
        'prefer-promise-reject-errors': ERROR,
        'radix': DISABLE,
        'require-await': WARN,
        'vars-on-top': DISABLE,
        'wrap-iife': [ERROR, 'any'],
        'yoda': ERROR,

        // Strict mode / http://eslint.org/docs/rules/#strict-mode
        'strict': DISABLE,

        // Variables / http://eslint.org/docs/rules/#variables
        'init-declarations': DISABLE,
        'no-catch-shadow': ERROR,
        'no-delete-var': ERROR,
        'no-label-var': ERROR,
        'no-restricted-globals': ERROR,
        'no-shadow': ERROR,
        'no-shadow-restricted-names': ERROR,
        'no-undef': ERROR,
        'no-undef-init': ERROR,
        'no-undefined': ERROR,
        'no-unused-vars': [ERROR, {'args': 'none'}],
        'no-use-before-define': ERROR,

        // Node.js and CommonJS / http://eslint.org/docs/rules/#nodejs-and-commonjs
        'callback-return': DISABLE,
        'global-require': DISABLE,
        'handle-callback-err': DISABLE,
        'no-buffer-constructor': DISABLE,
        'no-mixed-requires': DISABLE,
        'no-new-require': ERROR,
        'no-path-concat': DISABLE,
        'no-process-env': DISABLE,
        'no-process-exit': DISABLE,
        'no-restricted-modules': DISABLE,
        'no-sync': DISABLE,

        // Stylistic Issues / http://eslint.org/docs/rules/#stylistic-issues
        'array-bracket-newline': [ERROR, {'multiline': true}],
        'array-bracket-spacing': [ERROR, 'never'],
        'array-element-newline': DISABLE,
        'block-spacing': [ERROR, 'always'],
        'brace-style': [ERROR, '1tbs', {'allowSingleLine': true}],
        'camelcase': [ERROR, {'properties': 'never'}],
        'capitalized-comments': DISABLE,
        'comma-dangle': [ERROR, 'always-multiline'],
        'comma-spacing': [ERROR, {'before': false, 'after': true}],
        'comma-style': [ERROR, 'last'],
        'computed-property-spacing': [ERROR, 'never'],
        'consistent-this': [ERROR, 'self'],
        'eol-last': DISABLE,
        'func-call-spacing': [ERROR, "never"],
        'func-name-matching': ERROR,
        'func-names': DISABLE,
        'func-style': [ERROR, 'expression', {'allowArrowFunctions': true}],
        'id-blacklist': DISABLE,
        'id-length': [ERROR, {
            'min': 3,
            'max': 30,
            'properties': 'never',
            'exceptions': ['e', 'i', 'j', 'k', 'x', 'y', 'z', '$', '$$', '$f', '_']
        }],
        'id-match': DISABLE,
        'indent': [ERROR, 4, {'SwitchCase': 1}],
        'jsx-quotes': DISABLE,
        'key-spacing': [ERROR, {'afterColon': true, 'mode': 'minimum'}],
        'keyword-spacing': ERROR,
        'line-comment-position': DISABLE,
        'linebreak-style': ERROR,
        'lines-around-comment': [ERROR, {
            'beforeBlockComment': true,
            'beforeLineComment': false,
            'allowBlockStart': true,
            'allowObjectStart': true,
            'allowArrayStart': true
        }],
        'max-depth': [ERROR, 4],
        'max-len': [WARN, 120, 4],
        'max-lines': DISABLE,
        'max-params': [ERROR, 5],
        'max-nested-callbacks': [ERROR, 3],
        'max-statements': DISABLE,
        'max-statements-per-line': ERROR,
        'multiline-ternary': DISABLE,
        'new-cap': ERROR,
        'new-parens': ERROR,
        'newline-per-chained-call': [ERROR, {'ignoreChainWithDepth': 3}],
        'no-array-constructor': ERROR,
        'no-bitwise': DISABLE,
        'no-continue': DISABLE,
        'no-inline-comments': DISABLE,
        'no-lonely-if': ERROR,
        'no-mixed-operators': ERROR,
        'no-mixed-spaces-and-tabs': ERROR,
        'no-multiple-empty-lines': [ERROR, {'max': 2}],
        'no-negated-condition': WARN,
        'no-nested-ternary': WARN,
        'no-new-object': ERROR,
        'no-plusplus': DISABLE,
        'no-restricted-syntax': [ERROR, 'WithStatement'],
        'no-tabs': DISABLE,
        'no-ternary': DISABLE,
        'no-trailing-spaces': ERROR,
        'no-underscore-dangle': DISABLE,
        'no-unneeded-ternary': ERROR,
        'no-whitespace-before-property': ERROR,
        'nonblock-statement-body-position': DISABLE,
        'object-curly-newline': DISABLE,
        'object-curly-spacing': [ERROR, 'never'],
        'object-property-newline': [ERROR, {allowMultiplePropertiesPerLine: true}],
        'one-var': DISABLE,
        'one-var-declaration-per-line': DISABLE,
        'operator-assignment': DISABLE,
        'operator-linebreak': [ERROR, 'before'],
        'padded-blocks': DISABLE,
        'padding-line-between-statements': [ERROR, {blankLine: 'always', prev: '*', next: 'return'}],
        'quote-props': [ERROR, 'as-needed', {'keywords': true}],
        'quotes': [ERROR, 'single', 'avoid-escape'],
        'require-jsdoc': DISABLE,
        'semi': [ERROR, 'always'],
        'semi-spacing': [ERROR, {'before': false, 'after': true}],
        'semi-style': [ERROR, 'last'],
        'sort-vars': DISABLE,
        'space-before-blocks': ERROR,
        'space-before-function-paren': DISABLE,
        'space-in-parens': [ERROR, 'never'],
        'space-infix-ops': ERROR,
        'space-unary-ops': ERROR,
        'spaced-comment': [ERROR, 'always', {'exceptions': ['-+_']}],
        'switch-colon-spacing': ERROR,
        'template-tag-spacing': DISABLE,
        'unicode-bom': DISABLE,
        'wrap-regex': DISABLE,

        // ECMAScript 6 / http://eslint.org/docs/rules/#ecmascript-6
        'arrow-body-style': [DISABLE, 'as-needed', {requireReturnForObjectLiteral: false}],
        'arrow-parens': [ERROR, 'always'],
        'arrow-spacing': ERROR,
        'constructor-super': ERROR,
        'generator-star-spacing': [ERROR, {before: false, after: true}],
        'no-class-assign': ERROR,
        'no-confusing-arrow': ['error', {allowParens: true}],
        'no-const-assign': ERROR,
        'no-dupe-class-members': ERROR,
        'no-duplicate-imports': DISABLE,
        'no-new-symbol': ERROR,
        'no-restricted-imports': DISABLE,
        'no-this-before-super': ERROR,
        'no-useless-computed-key': ERROR,
        'no-useless-constructor': ERROR,
        'no-useless-rename': [ERROR, {ignoreDestructuring: false, ignoreImport: false, ignoreExport: false}],
        'no-var': ERROR,
        'object-shorthand': DISABLE,
        'prefer-arrow-callback': ERROR,
        'prefer-const': [ERROR, {destructuring: 'any', ignoreReadBeforeAssign: true}],
        'prefer-destructuring': DISABLE,
        'prefer-numeric-literals': DISABLE,
        'prefer-rest-params': DISABLE,
        'prefer-spread': ERROR,
        'prefer-template': ERROR,
        'require-yield': ERROR,
        'rest-spread-spacing': [ERROR, 'never'],
        'sort-imports': DISABLE,
        'symbol-description': ERROR,
        'template-curly-spacing': ERROR,
        'yield-star-spacing': [ERROR, 'after'],
    }
};